import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
            <script src="https://cdn.tailwindcss.com"></script>
            <link rel="icon" href="assets/favicon.png" type="image/x-icon" />
              <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" />
              {/* <style>
                .nav {
                  position: fixed;
                top: 0;
                left: 0;
                width: 100%;
                z-index: 999;
        }

                .active{
                  color:orange;
        }
              </style> */}
              <title>NEPCODER</title>
            </head>
            <body className={inter.className}>
              {children}
            </body>
          </html>
          );
}
